### ISSUE TITLE
API uses default methods

### ISSUE THREAD

**Issue by rmannibucau** [eclipse/microprofile-open-api#223] opened 2018-05-27 14:37 UTC
API uses default methods which leads to not use any implementation in some cases and therefore a wrong behavior. It should load a provider and delegate to it the execution instead.

**Comment by arthurdm** [comment] 2018-05-28 14:33
hey @rmannibucau - thanks for the feedback.   Can you please clarify which API you're referring to, and which scenario this is causing an incorrect behaviour?

**Comment by rmannibucau** [comment] 2018-05-28 14:48
Hello @arthurdm ,

OASFilter for instance.

Issue is if the API is present you can do a new OASFilter() {} and use the instance but nothing is implemented. For a spec API it is a good practise to keep the method not defaults until the default implementation is valid/optional (filter::init in servlet for instance can be a noop but OASFilter::filterPathItem can't).

**Comment by arthurdm** [comment] 2018-05-28 15:59
The reason behind the defaults is so that implementers of the `OASFilter` interface aren't forced to implement every method - they just pick the ones they are interested in, and the others are no-ops.  

This saved us from having to do add an abstract class implementation with the no-ops.

**Comment by rmannibucau** [comment] 2018-05-28 16:20
I got that point but the API is really big and therefore its scope is fully uncontrolled on the user side which means it will not be that portable at the end using defaults. We already had some bad surprises with defaults so probably saner to not do it again.

**Comment by arthurdm** [comment] 2018-05-29 13:46
What do you mean by `fully uncontrolled on the user side`?   The user overrides exactly what they want to override.  Why wouldn't this be portable?  The defaults are in the spec - that makes it `more` portable.

**Comment by rmannibucau** [comment] 2018-05-29 13:58
Not really. If that's true it means the design is a "put it all in the same bag" one and should probably be split. Using at runtime filter methods which don't filter anything is not very user friendly + it prevents runtime optimizations so it should probably be rethought deeper than the original context of this ticket :(.

**Comment by arthurdm** [comment] 2018-05-29 15:23
You're suggesting having an interface per method?

**Comment by rmannibucau** [comment] 2018-05-29 15:30
It would work for me.

**Comment by rmannibucau** [comment] 2018-05-29 16:37
I see but is copyingn the right way? Is it a big deal to do it in a way the user is less lost on its responsability?

**Comment by arthurdm** [comment] 2018-05-29 18:02
I think the way it is works fine.  If you really feel strongly about proposing a split of the methods, I can put this in the agenda for the next hangout on June 5th.

**Comment by arthurdm** [comment] 2018-06-05 17:31
hey @rmannibucau - at the hangout today we agreed that splitting each method of the current filter into its own interface is not desirable.  If you had another proposal in mind, please let us know via some code - that will be make things more clear.

**Comment by rmannibucau** [comment] 2018-06-05 18:07
Then minimum is to throw an exception if a method is not implemented and intended to be used by current processing cause it can lead to an undefined and undesired behavior. Extreme trivial example is if you add a new default method doing almost the same than another.

More generally, default methods are not a replacement of old adapters for end users.

**Comment by arthurdm** [comment] 2018-06-05 20:30
I can appreciate this point for general interfaces, but for the OASFilter there isn't any undesired behaviour by not implementing a particular method, as the corresponding OAS tree element remains as-is.

**Comment by rmannibucau** [comment] 2018-06-06 04:59
I understand where you are coming from but it looks very wrong for end users and it is very misleading IMHO.

Concretely what a user (i include myself here) wants is a visitor like filter API. An example is that i can want to filter parameters for a particular operation or path but not all matching params.

CDI configurators allows that whith a nicer API so instead of hiding completely the visitor you enable the user to browse the model through streams and just use java stream filters. It is way more natural than a copy of a vendor api and doesnt have this design issue when you have to implement it.

**Comment by arthurdm** [comment] 2018-06-06 14:20
@rmannibucau - can you please demonstrate your proposal with some code?   It's a bit hard to understand what is being proposed at the moment.   If you can show your alternative to the current OASFilter (not a general interface), that would help greatly.

**Comment by EricWittmann** [comment] 2018-06-06 16:13
This is not at all what I expected from this discussion!  Fascinating.

A builder approach is obviously quite different from a filter approach.  I don't have a strong opinion either way, TBH.  Another option would have been a full visitor pattern, which is similarly powerful.

Do we have any actual use cases that can inform this?  It seems to me that the filter pattern nicely addresses a pretty specific use case - the "shading" of elements based on some criteria.

A builder approach would be much more generic - you could mutate the model any way you wanted.  What is the goal?

If we stick with the filtering approach, I'm not sure I see a compelling argument to switch from default method implementations to a separate adapter class (which is where I thought this discussion was going).

**Comment by arthurdm** [comment] 2018-06-18 14:59
hey @rmannibucau - any comments on this?    @EricWittmann raised a good point that this proposed builder approach is a different type of conversation than the current filter.

**Comment by rmannibucau** [comment] 2018-06-18 15:14
I agree. The origin of that thread is that as a user the filter is quite misleading (I include myself but some colleagues as well in that statement). So aligning on something more fluent was the wish.

Also from an implementation perspective what do you do if you hit a default method without implementation? call it? This is not what do some specs (which prefer to throw an exception to avoid to let the user think it is working as expected silently).

Last point is that it is not proxy friendly since the default will not be handled leading to issues when users will try to compose the filters in a proxy. This is more a limit case but also something to keep in mind when designing an API now we have that new language feature, sadly not integrated in the whole JVM :(.

**Comment by OndrejM** [comment] 2018-07-12 13:04
HI @rmannibucau, this is a general concern and certainly doesn't apply only to openapi. Other MP APIs may be using default methods or will consider them in the future. I'm bringing this to the Arch board: https://github.com/eclipse/microprofile/issues/45

**Comment by rmannibucau** [comment] 2018-07-12 13:30
The nasty issue will come at the 1.1 time: you add a method, default indeed, user upgrades but don't realize the implementation is 1.1, it uses it since it is available and it doesn't do at all what is here. Same can happen to vendors BTW (did for jsonp). If a default doesn't implement the contract it must not exist IMHO.

**Comment by OndrejM** [comment] 2018-07-12 13:41
> If a default doesn't implement the contract it must not exist IMHO.

What do you mean by this, @rmannibucau ? I think that the default methods in OASFilter implement the contract, what's the problem there? Even if a new default method is added to the filter, if it just returns the argument, it would implement the contract, or not?

**Comment by rmannibucau** [comment] 2018-07-12 13:53
@OndrejM this one is more particular: the contract is very hard to understand for end users and the component (filter) is not needed at all on user land since you can already do that using plain java and streams in general.

**Comment by arthurdm** [comment] 2018-07-16 13:48
users don't call the filter - they just override the methods that they want to use.  This discussion is making this a lot harder and more general than it needs to be, IMO.

**Comment by rmannibucau** [comment] 2018-07-16 14:04
except there is no way a user knows what to understand and at the end it is faster and more controlled to just use streams to filter openapi in a jaxrs response filter or equivalent than implementing a custom oasis filter which is quite far from the end user semantic and more on the implementation side IMHO.

**Comment by arthurdm** [comment] 2018-07-16 15:14
This was discussed at the hangout today and we couldn't ultimately understand what the issue is with this *particular* case.  The OASFilter may have other issues with it (we agree on that), but the default implementation isn't one of them.  

As noted, @rmannibucau makes good points about general issues with user-invoked default methods and @OndrejM has correctly moved the discussed [here](https://github.com/eclipse/microprofile/issues/45).    Closing this one.

**Closed by arthurdm** 2018-07-16 15:14 UTC
Labels: api

**Comment by OndrejM** [comment] 2018-07-16 15:25
I think that the main concern is that the API can be simplified with streams and not that the default methods are used. This issue is closed corectly.

@rmannibucau, please raise another issue to reflect the ideas of using streams, ideally with a PR how to replace the filter functionality with a stream-based API
